defaults:
  db_url: DATABASE_URL
  batch_size: 500
  on_conflict: upsert

sources:
  - name: noaa_monthly_sample
    type: csv
    path: sample_data/small_sample.csv #sample_data/gsom_sample_csv.csv
    target_table: stg_noaa_monthly
    pk: [station, date]

    schema:
      station: str
      name: str
      date: datetime
      prcp: float
      snow: float
      tmax: float
      tmin: float
      awnd: float

    rules:
      - prcp >= 0
      - snow >= 0
      - tmax >= tmin

  - name: open_meteo_sample
    type: json
    path: sample_data/open_meteo_sample.json
    target_table: stg_open_meteo
    pk: [latitude, longitude, timestamp]

    schema:
      latitude: float
      longitude: float
      timestamp:  datetime

      temperature_2m: float
      apparent_temperature: float

      precipitation: float
      snowfall: float

      wind_speed_10m: float
      wind_gusts_10m: float

      relative_humidity_2m: float
      cloud_cover: float
      pressure_msl: float

    rules:
      - latitude >= -90
      - latitude <= 90
      - longitude >= -180
      - longitude <= 180

      - precipitation >= 0
      - snowfall >= 0

      - wind_speed_10m >= 0
      - wind_gusts_10m >= 0

